### ISSUE TITLE
[Flying backwards moves GameCanvas Out of bounds]

### ISSUE THREAD

**Issue by Coldfusionstorm** [Superkaj/Project#25]
Picture attached
![flyingbackwards](https://user-images.githubusercontent.com/34175537/35991434-80e256f2-0d07-11e8-835d-c3f3b8ac0d71.JPG)

**Comment by Superkaj** [comment]
Checking now

**Comment by Superkaj** [comment]
What Resolution do you use?
I cant recreate the bug.
You might not have the newest version.

**Comment by Superkaj** [comment]
Fixed
