### ISSUE TITLE
[Player viewport bug] background map clipping in botside.

### ISSUE THREAD

**Issue by Coldfusionstorm** [Superkaj/Project#4]
Som sagt, Spillet klipper det

![billede](https://user-images.githubusercontent.com/34175537/35674205-28317c68-0744-11e8-8b23-256ca312cf91.png)
 nederste af baggrunden af.

**Comment by Superkaj** [comment]
![billede](https://user-images.githubusercontent.com/15212188/35676111-dc8e5810-074a-11e8-8969-7311d92720f4.png)
Fixed, har også fixed de små borders der lige skulle have +2px osv.
